import { GearProcess, MeshPoint, ScenarioStep } from './types';

export const gears: GearProcess[] = [
  {
    id: 'vessel-schedule',
    name: 'Vessel Schedule',
    shortName: 'Schedule',
    tagline: 'Defines WHEN and WHERE',
    inputs: ['Itinerary from operations', 'Port agent confirmations', 'Charter/expedition calendar'],
    outputs: ['Crew change windows (port + date)', 'Immigration requirements per port', 'Berth assignments'],
    stages: [
      {
        id: 'vs-voyage-planning',
        name: 'Voyage Planning',
        description: 'Define itinerary — ports, dates, durations. Expedition schedule drives everything downstream.',
        duration: '6-12 months ahead',
        owner: 'Operations Director',
        automationNote: 'Import from expedition planning system or manual entry',
      },
      {
        id: 'vs-port-scheduling',
        name: 'Port Scheduling',
        description: 'Confirm berths, agent contacts, immigration/customs requirements per port. Some ports don\'t allow crew changes.',
        duration: '3-6 months ahead',
        owner: 'Port Operations',
        painPoints: ['Port agent contacts scattered across emails', 'Visa requirements not tracked per port'],
      },
      {
        id: 'vs-crew-change-windows',
        name: 'Crew Change Windows',
        description: 'Identify which ports allow crew changes based on: accessibility (airport proximity), customs (crew visa processing), timing (sufficient port time), logistics (hotel/transport availability).',
        duration: '2-3 months ahead',
        owner: 'Operations + Crewing',
        painPoints: ['Currently determined ad-hoc by Sam', 'No systematic evaluation of port suitability'],
        automationNote: 'System scores each port for crew change suitability based on airport distance, customs processing time, and historical success rate',
      },
      {
        id: 'vs-schedule-publish',
        name: 'Schedule Publication',
        description: 'Publish finalized schedule to all stakeholders: crew, travel team, captains, Lindblad HQ.',
        duration: 'Ongoing updates',
        owner: 'Operations',
        painPoints: ['Currently distributed via email attachment to 43 people', 'No version control — everyone may have different versions'],
        automationNote: 'Live dashboard replaces email distribution. Everyone sees the same current schedule.',
      },
    ],
  },
  {
    id: 'crew-rotation',
    name: 'Crew Rotation',
    shortName: 'Rotation',
    tagline: 'Determines WHO needs to change',
    inputs: ['Crew change windows from Vessel Schedule', 'Contract end dates', 'Leave requests', 'Emergency disembarkations'],
    outputs: ['Confirmed crew changes', 'Travel booking requests', 'Unfilled billet alerts → Hiring'],
    stages: [
      {
        id: 'cr-rotation-calendar',
        name: 'Rotation Calendar',
        description: 'Track contract lengths, rotation due dates, and leave schedules for every crew member across all vessels.',
        duration: 'Continuous',
        owner: 'Crewing Manager (Sam)',
        painPoints: [
          'Currently tracked in C&G spreadsheet — 1,660 rows across 4 vessel tabs',
          '74 position title variants for ~25 actual positions (typos like "Enginer Mechanic")',
          'No automated rotation due date alerts',
        ],
        automationNote: 'System tracks contract end dates and triggers alerts at 60/45/30 days before rotation due',
      },
      {
        id: 'cr-relief-pool',
        name: 'Relief Pool Review',
        description: 'Check available qualified relief crew in the pool. Match against position requirements, vessel class qualifications, and availability.',
        duration: '45-60 days before change',
        owner: 'Crewing Manager',
        painPoints: ['Relief pool lives in Sam\'s head + separate spreadsheet', 'No systematic qualification matching'],
        automationNote: 'System maintains relief pool with qualification profiles. Auto-matches against open billets.',
      },
      {
        id: 'cr-billet-matching',
        name: 'Billet Matching',
        description: 'Match available relief to open billets. Consider: qualifications (LEX matrix), vessel class experience, travel logistics, STCW rest requirements.',
        duration: '30-45 days before change',
        owner: 'Crewing Manager',
        painPoints: [
          'Matching is manual — Sam cross-references multiple spreadsheets',
          'No visibility into whether relief crew\'s certs are current',
          '38 of 63 upcoming crew changes currently have no flights (60%)',
        ],
        automationNote: 'System auto-checks all certifications against LEX matrix before allowing assignment. Red flag if any required cert is missing or expired.',
      },
      {
        id: 'cr-assignment',
        name: 'Assignment Confirmation',
        description: 'Confirm relief assignment. Notify: crew member, vessel captain, travel team, operations.',
        duration: '21-30 days before change',
        owner: 'Crewing Manager',
        automationNote: 'One-click assignment triggers notifications to all parties and initiates travel booking workflow',
      },
      {
        id: 'cr-travel-initiation',
        name: 'Travel Initiation',
        description: 'Trigger travel booking for confirmed crew change. Generate PNR request with: origin, destination, dates, crew preferences, budget parameters.',
        duration: '14-21 days before change',
        owner: 'Travel Coordinator',
        painPoints: [
          '3 crew changes within 7 days currently have no flights booked',
          'No automated alerts for unbooked travel',
          'Kelly can\'t trace refunds to crew members (Feb mystery credit incident)',
        ],
        automationNote: 'System auto-generates travel request when assignment confirmed. $20/PNR covers C Teleport booking, Lifeline rebooking, cost tracking, travel packet push.',
      },
    ],
  },
  {
    id: 'hiring-onboarding',
    name: 'Hiring & Onboarding',
    shortName: 'Hiring',
    tagline: 'Fills gaps when no relief available',
    inputs: ['Unfilled billet alerts from Crew Rotation', 'Position requirements from LEX matrix', 'Vessel class qualifications'],
    outputs: ['Deployment-ready crew → Training gate', 'Updated relief pool', 'Travel document readiness'],
    stages: [
      {
        id: 'ho-requisition',
        name: 'Requisition',
        description: 'Billet opens with no relief available. System creates hiring requisition with: position, vessel class, required certifications (from LEX matrix), target deployment date, port.',
        duration: 'Day 0',
        owner: 'Crewing Manager',
        painPoints: ['Currently tracked informally — "sailing short" notes in unfilled billets spreadsheet'],
        automationNote: 'Auto-generated when billet matching fails. Includes full cert requirements from LEX 2025 matrix.',
      },
      {
        id: 'ho-sourcing',
        name: 'Sourcing',
        description: 'Post to maritime job boards, contact recruitment agencies, circulate through internal referral network. Source against specific qualification requirements.',
        duration: '3-7 days',
        owner: 'Recruitment',
        automationNote: 'Track candidate pipeline with source attribution. Auto-screen against minimum cert requirements.',
      },
      {
        id: 'ho-screening',
        name: 'Screening',
        description: 'Resume review and initial qualification check. Verify MMC tonnage level matches vessel class (Quest/Venture/Explorer = 500 GRT, Sea Bird/Sea Lion = 100 GRT). Check STCW, TWIC status.',
        duration: '2-3 days',
        owner: 'Recruitment',
        painPoints: ['No systematic check against LEX matrix — qualifications verified informally'],
        automationNote: 'System compares candidate credentials against full LEX requirements. Flags gaps before interview.',
      },
      {
        id: 'ho-interview',
        name: 'Interview & References',
        description: 'Technical interview covering vessel-specific knowledge, safety procedures, expedition experience. Reference checks with previous employers.',
        duration: '3-5 days',
        owner: 'Hiring Manager',
      },
      {
        id: 'ho-offer',
        name: 'Offer & Acceptance',
        description: 'Generate offer letter with: position, vessel assignment, rotation schedule, compensation, start date. Candidate signs acceptance.',
        duration: '2-5 days',
        owner: 'HR / Crewing',
        automationNote: 'If Gusto-integrated: crew profile auto-creates in payroll system. No double-entry.',
      },
      {
        id: 'ho-preboarding',
        name: 'Pre-boarding Paperwork',
        description: 'Collect: I-9, W-4, tax documents, emergency contacts, company policy acknowledgments, union docs if applicable.',
        duration: '3-5 days',
        owner: 'HR',
        substages: [
          { id: 'ho-pb-i9', name: 'I-9 Verification', description: 'Employment eligibility verification', gate: true },
          { id: 'ho-pb-tax', name: 'Tax Documents', description: 'W-4, state withholding', gate: false },
          { id: 'ho-pb-emergency', name: 'Emergency Contacts', description: 'NOK and emergency contact information', gate: true },
          { id: 'ho-pb-policies', name: 'Policy Acknowledgment', description: 'Company policies, code of conduct, safety manual', gate: true },
        ],
        automationNote: 'Digital packet sent via portal link (token-based, no login). Status tracked per document.',
      },
      {
        id: 'ho-drug-alcohol',
        name: 'Drug & Alcohol Testing',
        description: 'Schedule pre-employment D&A test through Drug Free Vessel (consortium administrator). USCG/DOT panel. Results typically 24-72 hours.',
        duration: '3-7 days',
        owner: 'HR + Drug Free Vessel',
        gate: true,
        painPoints: ['D&A status not tracked in current system — HELM shows 325 missing certs including D&A'],
        automationNote: 'System tracks: test scheduled, specimen collected, results received, MRO reviewed. We make compliance seamless with Drug Free Vessel — they do the administration, we track the status.',
      },
      {
        id: 'ho-background',
        name: 'Background Check',
        description: 'Criminal background check, maritime sanctions screening, employment history verification.',
        duration: '5-10 days',
        owner: 'HR',
        gate: true,
        automationNote: 'Status pipeline: initiated → in progress → cleared / flagged',
      },
      {
        id: 'ho-credentials',
        name: 'Credential Collection & Audit',
        description: 'Collect all required certifications per LEX 2025 matrix. Quest/Venture/Explorer Captain needs 18 certs; even a Seasonal Deckhand needs 7. Verify each against requirements.',
        duration: '5-14 days',
        owner: 'Crewing',
        gate: true,
        painPoints: [
          'HELM shows 325 missing certifications with zero automated alerts',
          '30 expired certifications — no system notification',
          'LEX matrix has different requirements per vessel class — no automated matching',
        ],
        substages: [
          { id: 'ho-cr-mmc', name: 'MMC Verification', description: 'Merchant Mariner Credential — verify tonnage matches vessel class', gate: true },
          { id: 'ho-cr-stcw', name: 'STCW Certificates', description: 'BST, crowd management, crisis management as required by position', gate: true },
          { id: 'ho-cr-twic', name: 'TWIC Card', description: 'Transportation Worker Identification Credential', gate: true },
          { id: 'ho-cr-medical', name: 'Medical Certificate', description: 'USCG medical certificate (CG-719K)', gate: true },
          { id: 'ho-cr-specialty', name: 'Specialty Certifications', description: 'ECDIS, GMDSS, MedPIC, OLCC, ServSafe — per position and vessel class', gate: false },
        ],
        automationNote: 'System maps crew certs against LEX 2025 matrix automatically. Flags gaps with expiry tracking. Blocks crew change if required cert is missing.',
      },
      {
        id: 'ho-gap-remediation',
        name: 'Gap Remediation',
        description: 'If credential audit reveals gaps: schedule required training, renewals, or recertification courses. Track enrollment through completion.',
        duration: '7-21 days (varies)',
        owner: 'Training + Crewing',
        automationNote: 'Feeds into Training & Compliance gear. Training scheduled based on cert gap + deployment deadline.',
      },
      {
        id: 'ho-travel-docs',
        name: 'Travel Document Readiness',
        description: 'Verify: passport validity (6+ months), visa requirements for deployment port, TWIC for US ports, any port-specific credentials.',
        duration: '7-14 days',
        owner: 'Travel Coordinator',
        gate: true,
        substages: [
          { id: 'ho-td-passport', name: 'Passport Verification', description: 'Valid passport with 6+ months remaining', gate: true },
          { id: 'ho-td-visa', name: 'Visa Requirements', description: 'Check destination requirements, initiate applications if needed', gate: true },
          { id: 'ho-td-port', name: 'Port Credentials', description: 'Port-specific access credentials, TWIC verification', gate: false },
        ],
        automationNote: 'Visa requirement checker auto-generates checklist per destination. Lead time alerts for visa processing.',
      },
      {
        id: 'ho-deploy-ready',
        name: 'Deployment Ready',
        description: 'All gates passed: D&A clear, background clear, all certs verified against LEX matrix, travel docs confirmed. Crew member enters the relief pool as deployment-ready.',
        duration: 'Gate check',
        owner: 'Crewing Manager',
        gate: true,
        automationNote: 'System auto-checks all gates. Green = deploy. Any red = blocked with specific reason shown.',
      },
    ],
  },
  {
    id: 'training-compliance',
    name: 'Training & Compliance',
    shortName: 'Training',
    tagline: 'GATES whether anyone can board',
    inputs: ['New hire credential gaps from Hiring', 'Cert expiry dates from crew profiles', 'LEX 2025 requirements matrix', 'Regulatory changes'],
    outputs: ['Compliance status per crew member', 'Training completion → clears deployment gate', 'Expiry alerts → triggers renewal'],
    stages: [
      {
        id: 'tc-requirements-matrix',
        name: 'Requirements Matrix',
        description: 'Define certifications required per position per vessel class. Quest/Venture/Explorer (QTVE) has different requirements than Sea Bird/Sea Lion (SBSL).',
        duration: 'Annual review',
        owner: 'Compliance Officer',
        painPoints: ['Currently lives in a standalone Excel file (LEX 2025 Compliance Requirements Per Position)'],
        automationNote: 'Matrix loaded into system. When position assigned, system auto-maps required certs. 18 certs for QTVE Captain, 10 for SBSL Captain, 7 for Seasonal Deckhand.',
      },
      {
        id: 'tc-crew-audit',
        name: 'Crew Compliance Audit',
        description: 'Compare each crew member\'s current certifications against their position\'s requirements. Generate compliance score per person and per vessel.',
        duration: 'Continuous',
        owner: 'Compliance + Crewing',
        painPoints: [
          'HELM shows 325 missing certifications — no automated comparison',
          '30 expired certifications with no system alerts',
          'No fleet-wide compliance dashboard',
        ],
        automationNote: 'Automatic daily audit. Fleet compliance score visible on dashboard. Per-crew drill-down shows exactly which certs are current, expiring, or missing.',
      },
      {
        id: 'tc-gap-identification',
        name: 'Gap Identification',
        description: 'Flag specific gaps: missing cert, expired cert, cert expiring within 90/60/30 days. Prioritize by deployment urgency — crew changing in 14 days with an expired cert is critical.',
        duration: 'Continuous',
        owner: 'Compliance',
        automationNote: 'Tiered alerts: 90 days (info), 60 days (warning), 30 days (urgent), expired (critical/blocks crew change)',
      },
      {
        id: 'tc-training-schedule',
        name: 'Training Scheduling',
        description: 'Schedule required courses, recertification programs, renewal exams. Coordinate with training providers, manage enrollment.',
        duration: 'As needed',
        owner: 'Training Coordinator',
        automationNote: 'Track training provider catalog, enrollment deadlines, completion certificates. Link to specific cert gaps.',
      },
      {
        id: 'tc-cert-tracking',
        name: 'Certification Tracking',
        description: 'Track: enrollment → attendance → exam → pass/fail → cert issued → uploaded to profile. Full audit trail per certification.',
        duration: 'Per course',
        owner: 'Training Coordinator',
        automationNote: 'Document upload with expiry extraction. Cert automatically mapped to crew profile and compliance matrix.',
      },
      {
        id: 'tc-expiry-monitoring',
        name: 'Expiry Monitoring',
        description: 'Continuous monitoring of all certification expiry dates across the fleet. 405 crew × ~10 avg certs = ~4,000 expiry dates to track.',
        duration: 'Continuous',
        owner: 'System (automated)',
        painPoints: ['HELM has expiry data but sends zero automated alerts', 'Expired certs discovered at embarkation — too late'],
        automationNote: 'Automated monitoring. Alerts at configurable thresholds. Morning digest for compliance officer with upcoming expirations.',
      },
      {
        id: 'tc-compliance-gate',
        name: 'Compliance Gate',
        description: 'Final check before any crew change: all required certifications current per LEX matrix for the assigned position and vessel class. This is the lock on the door — no cert, no board.',
        duration: 'Instant check',
        owner: 'System (automated)',
        gate: true,
        automationNote: 'Hard gate: system will not complete crew change assignment if required cert is missing or expired. Soft warning for certs expiring during the rotation.',
      },
    ],
  },
];

export const meshPoints: MeshPoint[] = [
  {
    fromGear: 'vessel-schedule',
    toGear: 'crew-rotation',
    label: 'Crew Change Windows',
    trigger: 'Schedule published with crew change ports and dates',
    dataFlow: ['Port + date pairs', 'Immigration requirements', 'Logistical constraints (airport proximity, berth time)'],
  },
  {
    fromGear: 'crew-rotation',
    toGear: 'hiring-onboarding',
    label: 'Unfilled Billet Alert',
    trigger: 'Relief pool review finds no qualified relief for an open billet',
    dataFlow: ['Position + vessel class', 'Required certifications (LEX matrix)', 'Target deployment date + port', 'Urgency level'],
  },
  {
    fromGear: 'hiring-onboarding',
    toGear: 'training-compliance',
    label: 'Credential Gaps',
    trigger: 'New hire credential audit reveals missing or expired certifications',
    dataFlow: ['Crew member profile', 'Required certs vs. held certs', 'Deployment deadline', 'Gap remediation priority'],
  },
  {
    fromGear: 'training-compliance',
    toGear: 'crew-rotation',
    label: 'Compliance Cleared',
    trigger: 'All required certifications verified current — crew member cleared for deployment',
    dataFlow: ['Compliance status (all green)', 'Cert expiry dates for rotation planning', 'Any watch-specific qualifications'],
  },
  {
    fromGear: 'training-compliance',
    toGear: 'hiring-onboarding',
    label: 'Gap Remediation Required',
    trigger: 'Cert gap found that must be resolved before deployment',
    dataFlow: ['Specific cert gaps', 'Training course options', 'Estimated completion time', 'Impact on deployment date'],
  },
  {
    fromGear: 'crew-rotation',
    toGear: 'vessel-schedule',
    label: 'Crew Change Confirmed',
    trigger: 'Relief assigned, travel booked, compliance cleared — crew change locked in',
    dataFlow: ['Confirmed crew change details', 'Travel itineraries', 'Port agent coordination needs'],
  },
];

export const scenarioSteps: ScenarioStep[] = [
  {
    dayOffset: -45,
    gear: 'vessel-schedule',
    stageId: 'vs-crew-change-windows',
    title: 'Crew Change Window Identified',
    description: 'Quest arrives Juneau, AK on Jun 28. Port scored high for crew change: airport 15 min from dock, US port (no visa for US crew), 18-hour port stay. System flags this as crew change window.',
    highlight: 'info',
  },
  {
    dayOffset: -44,
    gear: 'crew-rotation',
    stageId: 'cr-rotation-calendar',
    title: 'Rotation Due Alert',
    description: 'Chief Mate contract ends Jun 30. System generates 45-day rotation alert. Current Chief Mate has been aboard 84 days of 90-day rotation.',
    highlight: 'warning',
  },
  {
    dayOffset: -43,
    gear: 'crew-rotation',
    stageId: 'cr-relief-pool',
    title: 'No Relief Available',
    description: 'Relief pool check: 2 qualified Chief Mates in pool, but both are currently deployed on other vessels. No available relief. System escalates to Hiring.',
    highlight: 'error',
  },
  {
    dayOffset: -42,
    gear: 'hiring-onboarding',
    stageId: 'ho-requisition',
    title: 'Requisition Auto-Created',
    description: 'System creates hiring requisition: Chief Mate, Quest/Venture/Explorer class, 18 certifications required per LEX 2025 matrix. Target deployment: Juneau, Jun 28. Urgency: HIGH (42 days).',
    highlight: 'info',
  },
  {
    dayOffset: -35,
    gear: 'hiring-onboarding',
    stageId: 'ho-sourcing',
    title: 'Candidate Sourced',
    description: 'Maritime recruitment agency submits candidate: experienced Chief Mate with 500 GRT Master endorsement, 8 years expedition vessel experience.',
    highlight: 'info',
  },
  {
    dayOffset: -32,
    gear: 'hiring-onboarding',
    stageId: 'ho-screening',
    title: 'Pre-Screen Against LEX Matrix',
    description: 'System auto-checks candidate\'s stated credentials against Chief Mate QTVE requirements (18 certs). 16 of 18 verified. Flags: ECDIS cert expired 3 months ago, Health Questionnaire not on file.',
    highlight: 'warning',
  },
  {
    dayOffset: -28,
    gear: 'hiring-onboarding',
    stageId: 'ho-interview',
    title: 'Interview Complete',
    description: 'Technical interview passed. Strong vessel knowledge, expedition experience with National Geographic fleet familiar. References verified with two previous employers.',
    highlight: 'success',
  },
  {
    dayOffset: -25,
    gear: 'hiring-onboarding',
    stageId: 'ho-offer',
    title: 'Offer Accepted',
    description: 'Offer letter generated with: Chief Mate, Quest, 90-day rotation, compensation per scale. Candidate signs same day. Gusto profile auto-created — no double-entry.',
    highlight: 'success',
  },
  {
    dayOffset: -24,
    gear: 'hiring-onboarding',
    stageId: 'ho-preboarding',
    title: 'Pre-boarding Packet Sent',
    description: 'Digital onboarding packet pushed via SMS + email: I-9, W-4, emergency contacts, policy acknowledgments. Token-based portal link — no login required. Status tracked per document.',
    highlight: 'info',
  },
  {
    dayOffset: -21,
    gear: 'hiring-onboarding',
    stageId: 'ho-drug-alcohol',
    title: 'D&A Test Scheduled',
    description: 'Pre-employment D&A test scheduled through Drug Free Vessel. USCG/DOT panel at approved collection site near candidate\'s home. Specimen collected same day.',
    highlight: 'info',
  },
  {
    dayOffset: -18,
    gear: 'hiring-onboarding',
    stageId: 'ho-drug-alcohol',
    title: 'D&A Results: CLEARED',
    description: 'Negative result received from MRO. D&A gate passed ✅. System updates compliance profile and clears this gate toward deployment.',
    highlight: 'success',
  },
  {
    dayOffset: -17,
    gear: 'hiring-onboarding',
    stageId: 'ho-background',
    title: 'Background Check Initiated',
    description: 'Criminal background, maritime sanctions screening, employment history verification initiated. Estimated 5-7 business days.',
    highlight: 'info',
  },
  {
    dayOffset: -13,
    gear: 'hiring-onboarding',
    stageId: 'ho-credentials',
    title: 'Credential Audit — GAP FOUND',
    description: 'Full LEX matrix check for Chief Mate QTVE: 16 of 18 certs verified ✅. ECDIS certificate EXPIRED (3 months ago) ❌. Health Questionnaire NOT ON FILE ❌. Two gates blocked.',
    highlight: 'error',
  },
  {
    dayOffset: -13,
    gear: 'training-compliance',
    stageId: 'tc-gap-identification',
    title: 'Gap Escalated to Training',
    description: 'Two gaps flagged to Training & Compliance gear: ECDIS recertification needed (2-day course), Health Questionnaire form required. Deployment deadline: 13 days. URGENT.',
    highlight: 'error',
  },
  {
    dayOffset: -12,
    gear: 'hiring-onboarding',
    stageId: 'ho-background',
    title: 'Background Check: CLEARED',
    description: 'Criminal background clear, no maritime sanctions, employment history verified. Background gate passed ✅.',
    highlight: 'success',
  },
  {
    dayOffset: -11,
    gear: 'training-compliance',
    stageId: 'tc-training-schedule',
    title: 'ECDIS Course Scheduled',
    description: 'ECDIS recertification course booked: 2-day intensive at approved maritime training center. Candidate enrolled for May 19-20. Health Questionnaire form sent to candidate.',
    highlight: 'info',
  },
  {
    dayOffset: -9,
    gear: 'training-compliance',
    stageId: 'tc-cert-tracking',
    title: 'ECDIS Course Complete — Cert Issued',
    description: 'Candidate completed ECDIS recertification. New certificate issued, valid 5 years. Uploaded to profile. Health Questionnaire also returned and filed. Both gaps closed.',
    highlight: 'success',
  },
  {
    dayOffset: -8,
    gear: 'training-compliance',
    stageId: 'tc-compliance-gate',
    title: 'COMPLIANCE GATE: ALL CLEAR ✅',
    description: 'All 18 certifications verified current per LEX 2025 matrix for Chief Mate QTVE. Compliance gate passed. Crew member cleared for deployment.',
    highlight: 'success',
  },
  {
    dayOffset: -8,
    gear: 'crew-rotation',
    stageId: 'cr-billet-matching',
    title: 'Billet Assignment Confirmed',
    description: 'New Chief Mate assigned to Quest. All gates passed: D&A ✅, Background ✅, Compliance ✅, Travel Docs ✅. Assignment locked. Notifications sent to: candidate, Captain, Sam, operations.',
    highlight: 'success',
  },
  {
    dayOffset: -7,
    gear: 'crew-rotation',
    stageId: 'cr-travel-initiation',
    title: 'Travel Booking Triggered',
    description: 'Travel request auto-generated: fly candidate to Juneau, AK. Arrive Jun 27 (day before embark for rest compliance). Hotel: nearest to port. Ground transport: port shuttle. $20 PNR fee covers everything.',
    highlight: 'info',
  },
  {
    dayOffset: -5,
    gear: 'crew-rotation',
    stageId: 'cr-travel-initiation',
    title: 'Travel Packet Pushed',
    description: 'Complete travel packet sent via SMS + email: flight itinerary, hotel confirmation, ground transport details, port agent contact, vessel berth location, embarkation time. Token-based portal link for updates.',
    highlight: 'success',
  },
  {
    dayOffset: -1,
    gear: 'vessel-schedule',
    stageId: 'vs-crew-change-windows',
    title: 'Crew Member Arrives Juneau',
    description: 'New Chief Mate arrives Juneau airport 4:30 PM. Port shuttle to hotel. Rest period begins (STCW compliant). Vessel arrives 6:00 AM next morning.',
    highlight: 'info',
  },
  {
    dayOffset: 0,
    gear: 'vessel-schedule',
    stageId: 'vs-schedule-publish',
    title: 'CREW CHANGE EXECUTED ✅',
    description: 'New Chief Mate boards Quest at 8:00 AM. Outgoing Chief Mate disembarks. Both sign the crew change log. System updates: roster, billet assignment, rotation calendar. Next rotation alert set for Day 90. Full cycle complete.',
    highlight: 'success',
  },
];

// Pain points from real data to highlight on the system view
export const realDataHighlights = {
  vesselSchedule: {
    stat: '43 recipients',
    detail: 'Schedule distributed via email attachment — no live dashboard',
  },
  crewRotation: {
    stat: '74 position variants',
    detail: '"Enginer Mechanic", "Seassonal Steward" — no controlled vocabulary',
  },
  hiringOnboarding: {
    stat: '38 / 63 unbooked',
    detail: '60% of upcoming crew changes have no flights (3 within 7 days)',
  },
  trainingCompliance: {
    stat: '325 + 30',
    detail: '325 missing certifications + 30 expired — HELM sends zero alerts',
  },
};
