import { CrewMember, Voyage, WatchEntry, FlightOption, CrewChange, CostEvent, TravelSearchCriteria, TravelOption, CrewLogisticsPlan, TravelPacket, VisaRequest, PortHotel } from './types';

export const vessel = {
  name: 'M/V HATCHLING',
  class: 'SANSU Bender Class',
  flag: 'US',
  imo: '9876543',
  callSign: 'WDC4567',
  homePort: 'Norfolk, VA',
  grossTonnage: '4,200 GT',
  length: '280 ft',
  watchPattern: '4on8off' as const,
  departments: ['Deck', 'Engine'],
  positions: [
    { title: 'Captain', department: 'Deck', count: 1 },
    { title: 'Chief Mate', department: 'Deck', count: 1 },
    { title: 'Third Mate', department: 'Deck', count: 1 },
    { title: 'Deckhand', department: 'Deck', count: 3 },
    { title: 'Engineer', department: 'Engine', count: 3 },
  ],
};

export const currentCrew: CrewMember[] = [
  {
    id: 'c1', name: 'Sarah Blackwood', position: 'Captain', department: 'Deck',
    status: 'on_board', homeAirport: 'BOS', phone: '(617) 555-0142', email: 'sblackwood@standingtide.com',
    seaDays: 2847, rotationWeeks: 6,
    credentials: [
      { name: 'Master 1600 GRT', number: 'MMC-2019-44821', issueDate: '2019-06-15', expiryDate: '2029-06-15', status: 'valid' },
      { name: 'STCW', number: 'STCW-2020-11234', issueDate: '2020-03-01', expiryDate: '2025-03-01', status: 'expiring_soon' },
      { name: 'TWIC', number: 'TWC-8834521', issueDate: '2022-01-10', expiryDate: '2027-01-10', status: 'valid' },
      { name: 'Medical Certificate', number: 'MED-2024-001', issueDate: '2024-01-15', expiryDate: '2026-01-15', status: 'valid' },
    ],
  },
  {
    id: 'c2', name: 'Mike Reeves', position: 'Chief Mate', department: 'Deck',
    status: 'on_board', homeAirport: 'JAX', phone: '(904) 555-0298', email: 'mreeves@standingtide.com',
    seaDays: 1923, rotationWeeks: 6,
    credentials: [
      { name: 'Chief Mate 1600 GRT', number: 'MMC-2020-55912', issueDate: '2020-08-20', expiryDate: '2030-08-20', status: 'valid' },
      { name: 'STCW', number: 'STCW-2021-22345', issueDate: '2021-04-10', expiryDate: '2026-04-10', status: 'valid' },
      { name: 'TWIC', number: 'TWC-9945632', issueDate: '2023-05-20', expiryDate: '2028-05-20', status: 'valid' },
      { name: 'Medical Certificate', number: 'MED-2024-018', issueDate: '2024-03-01', expiryDate: '2026-03-01', status: 'valid' },
    ],
  },
  {
    id: 'c3', name: 'Tom Halverson', position: 'Third Mate', department: 'Deck',
    status: 'on_board', homeAirport: 'SEA', phone: '(206) 555-0371', email: 'thalverson@standingtide.com',
    seaDays: 892, rotationWeeks: 6,
    credentials: [
      { name: 'Third Mate Unlimited', number: 'MMC-2022-67234', issueDate: '2022-02-14', expiryDate: '2032-02-14', status: 'valid' },
      { name: 'STCW', number: 'STCW-2022-33456', issueDate: '2022-05-01', expiryDate: '2027-05-01', status: 'valid' },
      { name: 'TWIC', number: 'TWC-1156743', issueDate: '2022-07-15', expiryDate: '2027-07-15', status: 'valid' },
      { name: 'Medical Certificate', number: 'MED-2025-007', issueDate: '2025-01-10', expiryDate: '2027-01-10', status: 'valid' },
    ],
  },
  {
    id: 'c4', name: 'Chris Park', position: 'Deckhand', department: 'Deck',
    status: 'on_board', homeAirport: 'ORF', phone: '(757) 555-0183', email: 'cpark@standingtide.com',
    seaDays: 456, rotationWeeks: 4,
    credentials: [
      { name: 'AB Special', number: 'MMC-2023-78345', issueDate: '2023-06-01', expiryDate: '2028-06-01', status: 'valid' },
      { name: 'TWIC', number: 'TWC-2267854', issueDate: '2023-08-10', expiryDate: '2028-08-10', status: 'valid' },
    ],
  },
  {
    id: 'c5', name: 'Ana Morales', position: 'Deckhand', department: 'Deck',
    status: 'on_board', homeAirport: 'MIA', phone: '(305) 555-0492', email: 'amorales@standingtide.com',
    seaDays: 612, rotationWeeks: 4,
    credentials: [
      { name: 'AB Special', number: 'MMC-2022-89456', issueDate: '2022-09-15', expiryDate: '2027-09-15', status: 'valid' },
      { name: 'TWIC', number: 'TWC-3378965', issueDate: '2022-11-20', expiryDate: '2027-11-20', status: 'valid' },
    ],
  },
  {
    id: 'c6', name: 'Jake Neilson', position: 'Deckhand', department: 'Deck',
    status: 'on_board', homeAirport: 'BWI', phone: '(410) 555-0567', email: 'jneilson@standingtide.com',
    seaDays: 289, rotationWeeks: 4,
    credentials: [
      { name: 'OS', number: 'MMC-2024-90567', issueDate: '2024-01-20', expiryDate: '2029-01-20', status: 'valid' },
      { name: 'TWIC', number: 'TWC-4489076', issueDate: '2024-02-15', expiryDate: '2029-02-15', status: 'valid' },
    ],
  },
  {
    id: 'c7', name: 'Rachel Torres', position: 'Engineer', department: 'Engine',
    status: 'on_board', homeAirport: 'IAH', phone: '(713) 555-0634', email: 'rtorres@standingtide.com',
    seaDays: 1567, rotationWeeks: 6,
    credentials: [
      { name: 'Chief Engineer Limited', number: 'MMC-2020-01678', issueDate: '2020-11-01', expiryDate: '2030-11-01', status: 'valid' },
      { name: 'STCW', number: 'STCW-2021-44567', issueDate: '2021-01-15', expiryDate: '2026-01-15', status: 'valid' },
      { name: 'TWIC', number: 'TWC-5590187', issueDate: '2021-03-20', expiryDate: '2026-03-20', status: 'expiring_soon' },
      { name: 'Medical Certificate', number: 'MED-2024-031', issueDate: '2024-05-01', expiryDate: '2026-05-01', status: 'valid' },
    ],
  },
  {
    id: 'c8', name: "Dave O'Brien", position: 'Engineer', department: 'Engine',
    status: 'on_board', homeAirport: 'PHL', phone: '(215) 555-0721', email: 'dobrien@standingtide.com',
    seaDays: 1034, rotationWeeks: 6,
    credentials: [
      { name: 'Asst Engineer Limited', number: 'MMC-2021-12789', issueDate: '2021-05-10', expiryDate: '2031-05-10', status: 'valid' },
      { name: 'STCW', number: 'STCW-2021-55678', issueDate: '2021-07-01', expiryDate: '2026-07-01', status: 'valid' },
      { name: 'TWIC', number: 'TWC-6601298', issueDate: '2023-09-05', expiryDate: '2028-09-05', status: 'valid' },
    ],
  },
  {
    id: 'c9', name: 'Kyle Fischer', position: 'Engineer', department: 'Engine',
    status: 'on_board', homeAirport: 'CHS', phone: '(843) 555-0856', email: 'kfischer@standingtide.com',
    seaDays: 567, rotationWeeks: 4,
    credentials: [
      { name: 'QMED', number: 'MMC-2023-23890', issueDate: '2023-03-15', expiryDate: '2028-03-15', status: 'valid' },
      { name: 'TWIC', number: 'TWC-7712309', issueDate: '2023-04-20', expiryDate: '2028-04-20', status: 'valid' },
    ],
  },
];

export const reliefCrew: CrewMember[] = [
  {
    id: 'r1', name: 'Dave Winters', position: 'Captain', department: 'Deck',
    status: 'available', homeAirport: 'PWM', phone: '(207) 555-0143', email: 'dwinters@standingtide.com',
    seaDays: 3102, rotationWeeks: 6,
    credentials: [
      { name: 'Master 1600 GRT', number: 'MMC-2018-33710', issueDate: '2018-04-01', expiryDate: '2028-04-01', status: 'valid' },
      { name: 'STCW', number: 'STCW-2019-00123', issueDate: '2019-06-15', expiryDate: '2029-06-15', status: 'valid' },
      { name: 'TWIC', number: 'TWC-0023410', issueDate: '2021-11-01', expiryDate: '2026-11-01', status: 'valid' },
      { name: 'Medical Certificate', number: 'MED-2025-002', issueDate: '2025-02-01', expiryDate: '2027-02-01', status: 'valid' },
    ],
  },
  {
    id: 'r2', name: 'Lisa Chen', position: 'Chief Mate', department: 'Deck',
    status: 'available', homeAirport: 'SFO', phone: '(415) 555-0276', email: 'lchen@standingtide.com',
    seaDays: 1745, rotationWeeks: 6,
    credentials: [
      { name: 'Chief Mate 1600 GRT', number: 'MMC-2021-44823', issueDate: '2021-01-10', expiryDate: '2031-01-10', status: 'valid' },
      { name: 'STCW', number: 'STCW-2021-11234', issueDate: '2021-03-20', expiryDate: '2026-03-20', status: 'valid' },
      { name: 'TWIC', number: 'TWC-1134521', issueDate: '2022-06-15', expiryDate: '2027-06-15', status: 'valid' },
      { name: 'Medical Certificate', number: 'MED-2024-042', issueDate: '2024-07-01', expiryDate: '2026-07-01', status: 'valid' },
    ],
  },
  {
    id: 'r3', name: 'Andy Brooks', position: 'Third Mate', department: 'Deck',
    status: 'available', homeAirport: 'ATL', phone: '(404) 555-0389', email: 'abrooks@standingtide.com',
    seaDays: 634, rotationWeeks: 6,
    credentials: [
      { name: 'Third Mate Unlimited', number: 'MMC-2023-55934', issueDate: '2023-05-01', expiryDate: '2033-05-01', status: 'valid' },
      { name: 'STCW', number: 'STCW-2023-22345', issueDate: '2023-06-15', expiryDate: '2028-06-15', status: 'valid' },
      { name: 'TWIC', number: 'TWC-2245632', issueDate: '2023-07-01', expiryDate: '2028-07-01', status: 'valid' },
      { name: 'Medical Certificate', number: 'MED-2024-056', issueDate: '2024-09-15', expiryDate: '2026-09-15', status: 'valid' },
    ],
  },
  {
    id: 'r4', name: 'Sam Butler', position: 'Deckhand', department: 'Deck',
    status: 'available', homeAirport: 'RDU', phone: '(919) 555-0412', email: 'sbutler@standingtide.com',
    seaDays: 378, rotationWeeks: 4,
    credentials: [
      { name: 'AB Special', number: 'MMC-2023-67045', issueDate: '2023-08-01', expiryDate: '2028-08-01', status: 'valid' },
      { name: 'TWIC', number: 'TWC-3356743', issueDate: '2023-09-10', expiryDate: '2028-09-10', status: 'valid' },
    ],
  },
  {
    id: 'r5', name: 'Jen Murphy', position: 'Engineer', department: 'Engine',
    status: 'available', homeAirport: 'BNA', phone: '(615) 555-0598', email: 'jmurphy@standingtide.com',
    seaDays: 1289, rotationWeeks: 6,
    credentials: [
      { name: 'Chief Engineer Limited', number: 'MMC-2021-78156', issueDate: '2021-09-01', expiryDate: '2031-09-01', status: 'valid' },
      { name: 'STCW', number: 'STCW-2022-33456', issueDate: '2022-01-15', expiryDate: '2027-01-15', status: 'valid' },
      { name: 'TWIC', number: 'TWC-4467854', issueDate: '2022-03-20', expiryDate: '2027-03-20', status: 'valid' },
      { name: 'Medical Certificate', number: 'MED-2024-067', issueDate: '2024-11-01', expiryDate: '2026-11-01', status: 'valid' },
    ],
  },
];

export const activeVoyage: Voyage = {
  id: 'v1',
  name: 'Norfolk → Bermuda → Norfolk',
  departure: 'Norfolk, VA',
  arrival: 'Hamilton, Bermuda',
  departureDate: '2026-05-10',
  arrivalDate: '2026-05-18',
  status: 'active',
  distance: '640 nm',
  waypoints: ['Chesapeake Bay Pilot Station', 'Cape Henry', 'Open Atlantic', 'Town Cut, St. George\'s', 'Hamilton Harbor'],
};

export const watchSchedule: WatchEntry[] = [
  { watch: '0000–0400', time: 'Mid Watch', officer: 'Tom Halverson (3/M)', crew: ['Jake Neilson (DH)', 'Kyle Fischer (ENG)'], notes: 'Nav lights checked, radar operational' },
  { watch: '0400–0800', time: 'Morning Watch', officer: 'Mike Reeves (C/M)', crew: ['Chris Park (DH)', "Dave O'Brien (ENG)"], notes: 'Sunrise 0612, visibility 10nm+' },
  { watch: '0800–1200', time: 'Forenoon Watch', officer: 'Sarah Blackwood (CPT)', crew: ['Ana Morales (DH)', 'Rachel Torres (ENG)'], notes: 'Captain has the conn, morning briefing 0830' },
  { watch: '1200–1600', time: 'Afternoon Watch', officer: 'Tom Halverson (3/M)', crew: ['Jake Neilson (DH)', 'Kyle Fischer (ENG)'], notes: 'Noon position report filed' },
  { watch: '1600–2000', time: 'First Dog / Second Dog', officer: 'Mike Reeves (C/M)', crew: ['Chris Park (DH)', "Dave O'Brien (ENG)"], notes: 'Sunset 1945, transition to night steaming' },
  { watch: '2000–0000', time: 'Evening Watch', officer: 'Sarah Blackwood (CPT)', crew: ['Ana Morales (DH)', 'Rachel Torres (ENG)'], notes: 'Night orders posted' },
];

export const flightOptions: FlightOption[] = [
  { id: 'f1', airline: 'United', flight: 'UA 1847', depart: 'SFO', arrive: 'BDA', departTime: 'May 16, 0715', arriveTime: 'May 16, 1845', price: 587, fareType: 'Marine Fare', stops: 1 },
  { id: 'f2', airline: 'Delta', flight: 'DL 2103', depart: 'SFO', arrive: 'BDA', departTime: 'May 16, 0930', arriveTime: 'May 16, 2130', price: 612, fareType: 'Marine Fare', stops: 1 },
  { id: 'f3', airline: 'American', flight: 'AA 943', depart: 'SFO', arrive: 'BDA', departTime: 'May 16, 0610', arriveTime: 'May 16, 1720', price: 723, fareType: 'Standard', stops: 1 },
];

export const rebookOptions: FlightOption[] = [
  { id: 'f4', airline: 'United', flight: 'UA 1849', depart: 'SFO', arrive: 'BDA', departTime: 'May 18, 0715', arriveTime: 'May 18, 1845', price: 587, fareType: 'Marine Fare', stops: 1 },
  { id: 'f5', airline: 'Delta', flight: 'DL 2105', depart: 'SFO', arrive: 'BDA', departTime: 'May 18, 0855', arriveTime: 'May 18, 2040', price: 598, fareType: 'Marine Fare', stops: 1 },
];

// ── Cost Events for Kelly's Change Portal ──────────────────
export const costEvents: CostEvent[] = [
  // === Voyage 1: Norfolk → Bermuda (current) ===
  // Lisa Chen original booking
  {
    id: 'ce1', date: '2026-05-01 09:15', type: 'booking',
    crewMemberId: 'r2', crewMemberName: 'Lisa Chen', voyageId: 'v1', voyageName: 'Norfolk → Bermuda',
    description: 'Initial flight booking — relief C/M crew change',
    vendor: 'United Airlines', originalAmount: 0, newAmount: 587, delta: 587,
    refundStatus: 'not_applicable', refundAmount: 0,
    approvedBy: 'System', approvalStatus: 'auto_approved',
    reason: 'Scheduled crew change — Mike Reeves rotating off after 6-week hitch',
    notes: 'Marine fare applied via C Teleport', pnr: 'UABX47', flightInfo: 'UA 1847 SFO→JFK→BDA May 16',
  },
  // Voyage delay triggers rebooking
  {
    id: 'ce2', date: '2026-05-12 14:30', type: 'change',
    crewMemberId: 'r2', crewMemberName: 'Lisa Chen', voyageId: 'v1', voyageName: 'Norfolk → Bermuda',
    description: 'Flight change — vessel arrival delayed 2 days (weather)',
    vendor: 'United Airlines', originalAmount: 587, newAmount: 587, delta: 0,
    refundStatus: 'not_applicable', refundAmount: 0,
    approvedBy: 'Capt. Blackwood', approvalStatus: 'approved',
    reason: 'Weather delay — ETA shifted from May 17 to May 19',
    relatedEventId: 'ce1',
    notes: 'Same fare, date change only. Marine fare flexibility — no change fee.', pnr: 'UABX47', flightInfo: 'UA 1849 SFO→JFK→BDA May 18',
  },
  // Lisa medical cancellation
  {
    id: 'ce3', date: '2026-05-14 08:45', type: 'cancellation',
    crewMemberId: 'r2', crewMemberName: 'Lisa Chen', voyageId: 'v1', voyageName: 'Norfolk → Bermuda',
    description: 'Flight cancelled — crew member medical issue',
    vendor: 'United Airlines', originalAmount: 587, newAmount: 0, delta: -587,
    refundStatus: 'pending', refundAmount: 587,
    approvedBy: 'Capt. Blackwood', approvalStatus: 'approved',
    reason: 'Lisa Chen — medical issue, unable to travel. Replacement needed.',
    relatedEventId: 'ce2',
    notes: 'Full refund requested on marine fare. Processing 5-7 business days.', pnr: 'UABX47', flightInfo: 'UA 1849 SFO→JFK→BDA May 18 — CANCELLED',
  },
  // Andy Brooks replacement booking
  {
    id: 'ce4', date: '2026-05-14 10:20', type: 'booking',
    crewMemberId: 'r3', crewMemberName: 'Andy Brooks', voyageId: 'v1', voyageName: 'Norfolk → Bermuda',
    description: 'Replacement flight booking — acting 3/M as C/M replacement plan',
    vendor: 'Delta Airlines', originalAmount: 0, newAmount: 498, delta: 498,
    refundStatus: 'not_applicable', refundAmount: 0,
    approvedBy: 'Capt. Blackwood', approvalStatus: 'approved',
    reason: 'Tom Halverson promoted to acting C/M. Andy Brooks called as 3/M relief.',
    notes: 'Marine fare applied. Andy confirmed available, credentials verified.', pnr: 'DLKM92', flightInfo: 'DL 2105 ATL→BDA May 18',
  },
  // Dave Winters (relief captain for next hitch)
  {
    id: 'ce5', date: '2026-04-28 11:00', type: 'booking',
    crewMemberId: 'r1', crewMemberName: 'Dave Winters', voyageId: 'v1', voyageName: 'Norfolk → Bermuda',
    description: 'Flight booking — relief Captain for next rotation',
    vendor: 'JetBlue', originalAmount: 0, newAmount: 512, delta: 512,
    refundStatus: 'not_applicable', refundAmount: 0,
    approvedBy: 'System', approvalStatus: 'auto_approved',
    reason: 'Scheduled rotation — Capt. Blackwood rotating off after arrival in Bermuda',
    notes: 'Standard booking, crew change in Hamilton.', pnr: 'JBPW31', flightInfo: 'B6 412 PWM→JFK→BDA May 20',
  },
  // Jen Murphy (relief engineer)
  {
    id: 'ce6', date: '2026-04-29 09:30', type: 'booking',
    crewMemberId: 'r5', crewMemberName: 'Jen Murphy', voyageId: 'v1', voyageName: 'Norfolk → Bermuda',
    description: 'Flight booking — relief Chief Engineer',
    vendor: 'American Airlines', originalAmount: 0, newAmount: 478, delta: 478,
    refundStatus: 'not_applicable', refundAmount: 0,
    approvedBy: 'System', approvalStatus: 'auto_approved',
    reason: 'Scheduled rotation — Rachel Torres completing 6-week hitch',
    notes: 'Marine fare applied. Flexible change policy.', pnr: 'AARN58', flightInfo: 'AA 1423 BNA→CLT→BDA May 20',
  },
  // Lisa refund processed
  {
    id: 'ce7', date: '2026-05-16 16:00', type: 'refund',
    crewMemberId: 'r2', crewMemberName: 'Lisa Chen', voyageId: 'v1', voyageName: 'Norfolk → Bermuda',
    description: 'Refund credited — UA 1849 cancellation',
    vendor: 'United Airlines', originalAmount: 587, newAmount: 0, delta: -587,
    refundStatus: 'credited', refundAmount: 587,
    approvedBy: 'United Airlines', approvalStatus: 'auto_approved',
    reason: 'Marine fare full refund processed',
    relatedEventId: 'ce3',
    notes: 'Refund credited to Standing Tide corporate card ending 4821.', pnr: 'UABX47', flightInfo: 'UA 1849 — refund complete',
  },
  // === Previous Voyage Example ===
  {
    id: 'ce8', date: '2026-04-05 10:00', type: 'booking',
    crewMemberId: 'c2', crewMemberName: 'Mike Reeves', voyageId: 'v0', voyageName: 'Jacksonville → Norfolk',
    description: 'Flight booking — joining vessel for current hitch',
    vendor: 'American Airlines', originalAmount: 0, newAmount: 345, delta: 345,
    refundStatus: 'not_applicable', refundAmount: 0,
    approvedBy: 'System', approvalStatus: 'auto_approved',
    reason: 'Scheduled crew change — beginning 6-week rotation',
    notes: '', pnr: 'AAHT63', flightInfo: 'AA 1220 JAX→ORF Apr 7',
  },
  {
    id: 'ce9', date: '2026-04-06 07:15', type: 'change',
    crewMemberId: 'c2', crewMemberName: 'Mike Reeves', voyageId: 'v0', voyageName: 'Jacksonville → Norfolk',
    description: 'Flight change — original flight cancelled by airline',
    vendor: 'American Airlines', originalAmount: 345, newAmount: 345, delta: 0,
    refundStatus: 'not_applicable', refundAmount: 0,
    approvedBy: 'System', approvalStatus: 'auto_approved',
    reason: 'AA 1220 cancelled — mechanical. Rebooked to AA 1224 same day.',
    relatedEventId: 'ce8',
    notes: 'No cost change. Airline-initiated rebooking.', pnr: 'AAHT63', flightInfo: 'AA 1224 JAX→ORF Apr 7',
  },
  {
    id: 'ce10', date: '2026-04-02 14:00', type: 'booking',
    crewMemberId: 'c3', crewMemberName: 'Tom Halverson', voyageId: 'v0', voyageName: 'Jacksonville → Norfolk',
    description: 'Flight booking — joining vessel for current hitch',
    vendor: 'Alaska Airlines', originalAmount: 0, newAmount: 412, delta: 412,
    refundStatus: 'not_applicable', refundAmount: 0,
    approvedBy: 'System', approvalStatus: 'auto_approved',
    reason: 'Scheduled crew change',
    notes: 'Marine fare applied.', pnr: 'ASKL77', flightInfo: 'AS 892 SEA→ORF Apr 6',
  },
];

export const initialCrewChange: CrewChange = {
  id: 'cc1',
  status: 'scheduled',
  offgoing: currentCrew[1], // Mike Reeves
  oncoming: reliefCrew[1], // Lisa Chen
  port: 'Hamilton, Bermuda',
  date: '2026-05-17',
  travelStatus: 'needs_booking',
  notes: [],
  history: [
    { time: '2026-05-01 09:00', event: 'Crew change scheduled — Mike Reeves (C/M) rotating off after 6-week hitch' },
    { time: '2026-05-01 09:01', event: 'Lisa Chen (C/M) selected as relief — credentials verified ✓' },
    { time: '2026-05-01 09:01', event: 'No double-booking conflicts detected across fleet' },
  ],
};

// ── Travel Planner Demo Data ───────────────────────────────────────

export const travelSearchScenarios: TravelSearchCriteria[] = [
  {
    crewMemberId: 'lisa-chen',
    crewMemberName: 'Lisa Chen',
    position: 'Chief Mate (Relief)',
    dateRangeStart: '2026-06-15',
    dateRangeEnd: '2026-06-18',
    originAirports: ['SFO', 'OAK', 'SJC'],
    destinationAirports: ['BDA'],
    maxBudget: 800,
    maxStops: 1,
    arriveBy: 'day_before',
    fareType: 'any',
  },
  {
    crewMemberId: 'andy-brooks',
    crewMemberName: 'Andy Brooks',
    position: 'Third Mate (Relief)',
    dateRangeStart: '2026-06-15',
    dateRangeEnd: '2026-06-18',
    originAirports: ['BOS', 'PVD'],
    destinationAirports: ['BDA'],
    maxBudget: 700,
    maxStops: 1,
    arriveBy: 'morning_of',
    fareType: 'marine',
  },
  {
    crewMemberId: 'dave-winters',
    crewMemberName: 'Dave Winters',
    position: 'Engineer (Relief)',
    dateRangeStart: '2026-06-14',
    dateRangeEnd: '2026-06-17',
    originAirports: ['JAX', 'SAV'],
    destinationAirports: ['BDA'],
    maxBudget: 650,
    maxStops: 2,
    arriveBy: 'day_before',
    fareType: 'any',
  },
];

export const travelOptionsForLisa: TravelOption[] = [
  {
    id: 'opt-1',
    airline: 'United',
    flightNumbers: ['UA 452', 'UA 1784'],
    originAirport: 'SFO',
    destinationAirport: 'BDA',
    departDate: '2026-06-16',
    departTime: '06:15',
    arriveDate: '2026-06-16',
    arriveTime: '17:50',
    stops: 1,
    layoverInfo: 'JFK (2h 10m)',
    travelTimeMinutes: 575,
    flightCost: 547,
    fareClass: 'Economy (Marine)',
    refundable: false,
    marineFare: true,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 781,
    tags: ['best_value', 'marine'],
  },
  {
    id: 'opt-2',
    airline: 'Delta',
    flightNumbers: ['DL 1184', 'DL 631'],
    originAirport: 'SFO',
    destinationAirport: 'BDA',
    departDate: '2026-06-16',
    departTime: '07:30',
    arriveDate: '2026-06-16',
    arriveTime: '19:45',
    stops: 1,
    layoverInfo: 'ATL (2h 00m)',
    travelTimeMinutes: 555,
    flightCost: 512,
    fareClass: 'Economy',
    refundable: false,
    marineFare: false,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 746,
    tags: ['budget'],
  },
  {
    id: 'opt-3',
    airline: 'American',
    flightNumbers: ['AA 876', 'AA 1487'],
    originAirport: 'SFO',
    destinationAirport: 'BDA',
    departDate: '2026-06-16',
    departTime: '07:40',
    arriveDate: '2026-06-16',
    arriveTime: '19:20',
    stops: 1,
    layoverInfo: 'CLT (1h 50m)',
    travelTimeMinutes: 520,
    flightCost: 598,
    fareClass: 'Economy',
    refundable: false,
    marineFare: false,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 832,
    tags: [],
  },
  {
    id: 'opt-4',
    airline: 'JetBlue',
    flightNumbers: ['B6 615', 'B6 247'],
    originAirport: 'SFO',
    destinationAirport: 'BDA',
    departDate: '2026-06-16',
    departTime: '08:00',
    arriveDate: '2026-06-16',
    arriveTime: '18:35',
    stops: 1,
    layoverInfo: 'BOS (1h 45m)',
    travelTimeMinutes: 515,
    flightCost: 524,
    fareClass: 'Blue (Marine)',
    refundable: false,
    marineFare: true,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 758,
    tags: ['fastest', 'marine'],
  },
  {
    id: 'opt-5',
    airline: 'Delta',
    flightNumbers: ['DL 2202', 'DL 477'],
    originAirport: 'SFO',
    destinationAirport: 'BDA',
    departDate: '2026-06-16',
    departTime: '09:30',
    arriveDate: '2026-06-16',
    arriveTime: '21:10',
    stops: 1,
    layoverInfo: 'JFK (2h 20m)',
    travelTimeMinutes: 580,
    flightCost: 684,
    fareClass: 'Flex Economy',
    refundable: true,
    marineFare: false,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 918,
    tags: ['most_flexible'],
  },
  {
    id: 'opt-6',
    airline: 'United',
    flightNumbers: ['UA 734', 'UA 1792'],
    originAirport: 'OAK',
    destinationAirport: 'BDA',
    departDate: '2026-06-15',
    departTime: '15:20',
    arriveDate: '2026-06-16',
    arriveTime: '05:15',
    stops: 1,
    layoverInfo: 'EWR (3h 10m)',
    travelTimeMinutes: 655,
    flightCost: 478,
    fareClass: 'Economy (Marine)',
    refundable: false,
    marineFare: true,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 712,
    tags: ['budget', 'marine'],
  },
];

export const travelOptionsForAndy: TravelOption[] = [
  {
    id: 'opt-a1',
    airline: 'JetBlue',
    flightNumbers: ['B6 587'],
    originAirport: 'BOS',
    destinationAirport: 'BDA',
    departDate: '2026-06-17',
    departTime: '08:10',
    arriveDate: '2026-06-17',
    arriveTime: '11:25',
    stops: 0,
    travelTimeMinutes: 135,
    flightCost: 412,
    fareClass: 'Blue (Marine)',
    refundable: false,
    marineFare: true,
    hotelNeeded: false,
    hotelCost: 0,
    groundTransportCost: 45,
    totalCost: 457,
    tags: ['best_value', 'fastest', 'direct', 'marine'],
  },
  {
    id: 'opt-a2',
    airline: 'American',
    flightNumbers: ['AA 1520'],
    originAirport: 'BOS',
    destinationAirport: 'BDA',
    departDate: '2026-06-17',
    departTime: '10:45',
    arriveDate: '2026-06-17',
    arriveTime: '14:00',
    stops: 0,
    travelTimeMinutes: 135,
    flightCost: 467,
    fareClass: 'Main Cabin',
    refundable: false,
    marineFare: false,
    hotelNeeded: false,
    hotelCost: 0,
    groundTransportCost: 45,
    totalCost: 512,
    tags: ['direct'],
  },
  {
    id: 'opt-a3',
    airline: 'Delta',
    flightNumbers: ['DL 410', 'DL 631'],
    originAirport: 'BOS',
    destinationAirport: 'BDA',
    departDate: '2026-06-16',
    departTime: '16:45',
    arriveDate: '2026-06-16',
    arriveTime: '22:10',
    stops: 1,
    layoverInfo: 'ATL (2h 15m)',
    travelTimeMinutes: 325,
    flightCost: 398,
    fareClass: 'Main Cabin',
    refundable: false,
    marineFare: false,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 632,
    tags: [],
  },
  {
    id: 'opt-a4',
    airline: 'JetBlue',
    flightNumbers: ['B6 591'],
    originAirport: 'BOS',
    destinationAirport: 'BDA',
    departDate: '2026-06-17',
    departTime: '12:30',
    arriveDate: '2026-06-17',
    arriveTime: '15:45',
    stops: 0,
    travelTimeMinutes: 135,
    flightCost: 548,
    fareClass: 'Blue Extra (Flex)',
    refundable: true,
    marineFare: false,
    hotelNeeded: false,
    hotelCost: 0,
    groundTransportCost: 45,
    totalCost: 593,
    tags: ['most_flexible', 'direct'],
  },
];

// ── Crew Logistics Plans ─────────────────────────────────────────────
export const crewLogisticsPlans: CrewLogisticsPlan[] = [
  {
    crewMemberId: 'r2',
    crewMemberName: 'Lisa Chen',
    position: 'Chief Mate (Relief)',
    tags: [
      { type: 'traveling_together', label: 'Traveling with Andy', icon: '🤝', detail: 'Shared taxi/minibus from Grotto Bay to Hamilton Harbour', linkedCrewId: 'r3' },
      { type: 'rest_required', label: 'Rest before watch', icon: '🕐', detail: 'SFO→BDA cross-country + international, 10+ hrs travel. STCW 10hr rest required. Watch-eligible: Jun 17 @ 0400' },
      { type: 'priority_arrival', label: 'Crew transport coordinator', icon: '📋', detail: 'Coordinating pre-arranged minibus from BDA Airport for deck relief crew' },
      { type: 'return_booked', label: 'Return flight booked', icon: '↩️', detail: 'UA 1785 BDA→JFK→SFO Jul 28 (end of rotation)' },
    ],
    hotel: {
      hotelName: 'Grotto Bay Beach Resort',
      address: '11 Blue Hole Hill, Hamilton Parish CR 04, Bermuda',
      confirmationNumber: 'GBR-884521',
      checkIn: '2026-06-16',
      checkOut: '2026-06-17',
      nightlyRate: 189,
      notes: 'Near BDA airport (5 min taxi). Hotel shuttle to Hamilton available at 0700. Breakfast included.',
    },
    groundTransport: {
      type: 'taxi',
      provider: 'Bermuda Island Taxi',
      confirmationNumber: 'BIT-JK8842',
      pickupTime: '2026-06-17 07:00',
      pickupLocation: 'Grotto Bay Beach Resort Lobby',
      dropoffLocation: 'Hamilton Harbour, Front Street Dock',
      cost: 55,
      capacity: 4,
      assignedCrew: ['r2', 'r3'],
    },
    arrivalTime: '2026-06-16 17:50',
    pickupSequence: 1,
    watchEligibleTime: '2026-06-17 04:00',
    notes: 'Lisa arrives at BDA, takes hotel shuttle to Grotto Bay. Next AM: shared taxi with Andy to Hamilton Harbour.',
  },
  {
    crewMemberId: 'r3',
    crewMemberName: 'Andy Brooks',
    position: 'Third Mate (Relief)',
    tags: [
      { type: 'traveling_together', label: 'Riding with Lisa', icon: '🤝', detail: 'Shared taxi from Grotto Bay to Hamilton Harbour AM of Jun 17', linkedCrewId: 'r2' },
      { type: 'rider', label: 'Passenger — shared taxi', icon: '🚐', detail: 'No separate ground transport needed', linkedCrewId: 'r2' },
      { type: 'first_arrival', label: 'First time in Bermuda', icon: '🆕', detail: 'Send harbour directions, vessel berth info, and port agent contact' },
      { type: 'comms_needed', label: 'Needs local SIM', icon: '📱', detail: 'Currently on T-Mobile — confirm Bermuda roaming or buy local SIM at BDA airport' },
    ],
    hotel: {
      hotelName: 'Grotto Bay Beach Resort',
      address: '11 Blue Hole Hill, Hamilton Parish CR 04, Bermuda',
      confirmationNumber: 'GBR-884522',
      checkIn: '2026-06-16',
      checkOut: '2026-06-17',
      nightlyRate: 189,
      notes: 'Same hotel as Lisa Chen. Room block rate applied.',
    },
    groundTransport: {
      type: 'crew_vehicle',
      pickupTime: '2026-06-17 07:00',
      pickupLocation: 'Grotto Bay Beach Resort Lobby',
      dropoffLocation: 'Hamilton Harbour, Front Street Dock',
      cost: 0,
      assignedCrew: ['r3'],
    },
    arrivalTime: '2026-06-17 11:25',
    pickupSequence: 2,
    watchEligibleTime: '2026-06-17 13:00',
    notes: 'BOS→BDA direct flight, arrives late morning. First time in Bermuda — send detailed harbour instructions.',
  },
  {
    crewMemberId: 'r1',
    crewMemberName: 'Dave Winters',
    position: 'Captain (Relief)',
    tags: [
      { type: 'priority_arrival', label: 'Priority — Captain handover', icon: '📋', detail: 'Must arrive before all other relief crew for bridge handover with Capt. Blackwood' },
      { type: 'heavy_gear', label: 'Heavy gear', icon: '🧳', detail: 'Personal sextant case + 2 checked bags. Need minibus or large taxi.' },
      { type: 'inter_vessel', label: 'From M/V PELICAN', icon: '🔄', detail: 'Transferring from sister vessel. Has current fleet SOPs and standing orders.' },
      { type: 'rest_required', label: 'Rest before watch', icon: '🕐', detail: 'Arriving from JAX via ATL after vessel discharge. 6hr rest minimum. Watch-eligible: Jun 16 @ 0000' },
      { type: 'return_booked', label: 'Return flight booked', icon: '↩️', detail: 'DL 632 BDA→ATL→JAX Aug 1 (end of rotation)' },
    ],
    hotel: {
      hotelName: 'Hamilton Princess & Beach Club',
      address: '76 Pitts Bay Rd, Hamilton HM 08, Bermuda',
      confirmationNumber: 'HPC-772134',
      checkIn: '2026-06-15',
      checkOut: '2026-06-16',
      nightlyRate: 279,
      notes: 'Captain-grade hotel. Walking distance to Hamilton Harbour and Front Street Dock.',
    },
    groundTransport: {
      type: 'taxi',
      provider: 'Bermuda Island Taxi',
      confirmationNumber: 'BIT-NR44521',
      pickupTime: '2026-06-15 17:00',
      pickupLocation: 'BDA Airport Taxi Stand',
      dropoffLocation: 'Hamilton Princess & Beach Club',
      cost: 45,
      capacity: 2,
      assignedCrew: ['r1'],
    },
    arrivalTime: '2026-06-15 16:40',
    pickupSequence: 0, // arrives day before
    watchEligibleTime: '2026-06-16 00:00',
    notes: 'Dave arrives a full day early for captain handover. Taxi from BDA to Hamilton Princess. Walks to vessel next morning. Meets Capt. Blackwood at 0800 Jun 16 for bridge handover.',
  },
  {
    crewMemberId: 'r5',
    crewMemberName: 'Jen Murphy',
    position: 'Chief Engineer (Relief)',
    tags: [
      { type: 'heavy_gear', label: 'Tools & equipment', icon: '🧳', detail: 'Personal tool roll + diagnostic laptop. Extra checked bag fee likely.' },
      { type: 'return_booked', label: 'Return: open', icon: '↩️', detail: 'One-way booked. Return TBD based on voyage schedule.' },
    ],
    hotel: {
      hotelName: 'Grotto Bay Beach Resort',
      address: '11 Blue Hole Hill, Hamilton Parish CR 04, Bermuda',
      confirmationNumber: 'GBR-884523',
      checkIn: '2026-06-16',
      checkOut: '2026-06-17',
      nightlyRate: 189,
      notes: 'Same hotel as deck relief crew. Engine room handover at 0700.',
    },
    groundTransport: {
      type: 'taxi',
      provider: 'Bermuda Island Taxi',
      pickupTime: '2026-06-17 06:15',
      pickupLocation: 'Grotto Bay Beach Resort',
      dropoffLocation: 'Hamilton Harbour, Front Street Dock',
      cost: 50,
      assignedCrew: ['r5'],
    },
    arrivalTime: '2026-06-16 18:30',
    pickupSequence: 3,
    watchEligibleTime: '2026-06-17 06:00',
    notes: 'Engine room handover with Rachel Torres at 0700. Separate from deck crew schedule. Taxi to Hamilton Harbour.',
  },
];

// ── Travel Packets ──────────────────────────────────────────────────
export const travelPackets: TravelPacket[] = [
  {
    id: 'pkt-1',
    crewMemberId: 'r1',
    crewMemberName: 'Dave Winters',
    position: 'Captain (Relief)',
    status: 'acknowledged',
    channel: 'both',
    sentAt: '2026-06-10 09:00',
    acknowledgedAt: '2026-06-10 09:42',
    version: 1,
    sections: { flights: true, hotel: true, groundTransport: true, portInfo: true, vesselBerth: true, emergencyContacts: true, visaInfo: false, pickupInstructions: true },
  },
  {
    id: 'pkt-2',
    crewMemberId: 'r2',
    crewMemberName: 'Lisa Chen',
    position: 'Chief Mate (Relief)',
    status: 'updated',
    channel: 'both',
    sentAt: '2026-06-10 09:00',
    acknowledgedAt: '2026-06-10 10:15',
    version: 2,
    sections: { flights: true, hotel: true, groundTransport: true, portInfo: true, vesselBerth: true, emergencyContacts: true, visaInfo: false, pickupInstructions: true },
    changes: [
      { field: 'Flight', oldValue: 'UA 452 Jun 16 @ 0615', newValue: 'UA 452 Jun 17 @ 0615 (delayed — weather)' },
      { field: 'Hotel Check-in', oldValue: 'Jun 16', newValue: 'Jun 17' },
    ],
  },
  {
    id: 'pkt-3',
    crewMemberId: 'r3',
    crewMemberName: 'Andy Brooks',
    position: 'Third Mate (Relief)',
    status: 'sent',
    channel: 'email',
    sentAt: '2026-06-12 14:30',
    version: 1,
    sections: { flights: true, hotel: true, groundTransport: true, portInfo: true, vesselBerth: true, emergencyContacts: true, visaInfo: false, pickupInstructions: true },
  },
  {
    id: 'pkt-4',
    crewMemberId: 'r5',
    crewMemberName: 'Jen Murphy',
    position: 'Chief Engineer (Relief)',
    status: 'draft',
    channel: 'both',
    version: 1,
    sections: { flights: true, hotel: true, groundTransport: false, portInfo: true, vesselBerth: true, emergencyContacts: true, visaInfo: false, pickupInstructions: false },
  },
];

// ── Visa Requests ───────────────────────────────────────────────────
export const visaRequests: VisaRequest[] = [
  {
    id: 'visa-1',
    crewMemberId: 'r2',
    crewMemberName: 'Lisa Chen',
    nationality: 'US',
    destinationCountry: 'Bermuda',
    destinationPort: 'Hamilton',
    visaType: 'Crew Transit Visa',
    status: 'not_required',
    documents: [],
    processingDays: 0,
    crewChangeDate: '2026-08-15',
    daysUntilCrewChange: 98,
    notes: 'US citizens exempt from visa for Bermuda. Valid passport required (exp 2028).',
    urgency: 'normal',
  },
  {
    id: 'visa-2',
    crewMemberId: 'r3',
    crewMemberName: 'Andy Brooks',
    nationality: 'US',
    destinationCountry: 'Bermuda',
    destinationPort: 'Hamilton',
    visaType: 'Crew Transit Visa',
    status: 'not_required',
    documents: [],
    processingDays: 0,
    crewChangeDate: '2026-08-15',
    daysUntilCrewChange: 98,
    notes: 'US citizens exempt. Passport valid through 2033.',
    urgency: 'normal',
  },
  {
    id: 'visa-3',
    crewMemberId: 'c4',
    crewMemberName: 'Chris Park',
    nationality: 'South Korea',
    destinationCountry: 'Bermuda',
    destinationPort: 'Hamilton',
    visaType: 'Crew Member Visa',
    status: 'processing',
    documents: [
      { name: 'Valid Passport', required: true, collected: true },
      { name: 'Seaman\'s Book', required: true, collected: true },
      { name: 'Letter of Invitation (Port Agent)', required: true, collected: true },
      { name: 'Passport Photos (2x)', required: true, collected: true },
      { name: 'Vessel Itinerary', required: true, collected: true },
      { name: 'Crew Employment Contract', required: true, collected: false, notes: 'Awaiting updated contract from HR' },
    ],
    submittedDate: '2026-04-28',
    processingDays: 21,
    crewChangeDate: '2026-06-17',
    daysUntilCrewChange: 40,
    portAgent: 'Meyer Agencies Ltd.',
    portAgentContact: '+1-441-295-4176',
    notes: 'South Korean nationals need crew visa for Bermuda. Submitted Apr 28, avg 21 day processing. Should clear by May 19.',
    urgency: 'normal',
  },
  {
    id: 'visa-4',
    crewMemberId: 'c5',
    crewMemberName: 'Ana Morales',
    nationality: 'Colombia',
    destinationCountry: 'Bermuda',
    destinationPort: 'Hamilton',
    visaType: 'Crew Member Visa',
    status: 'documents_gathering',
    documents: [
      { name: 'Valid Passport', required: true, collected: true },
      { name: 'Seaman\'s Book', required: true, collected: true },
      { name: 'Letter of Invitation (Port Agent)', required: true, collected: false, notes: 'Requested from Meyer Agencies, ETA 2 days' },
      { name: 'Passport Photos (2x)', required: true, collected: true },
      { name: 'Vessel Itinerary', required: true, collected: true },
      { name: 'Crew Employment Contract', required: true, collected: true },
      { name: 'Yellow Fever Vaccination Cert', required: true, collected: true },
    ],
    processingDays: 28,
    crewChangeDate: '2026-06-17',
    daysUntilCrewChange: 40,
    portAgent: 'Meyer Agencies Ltd.',
    portAgentContact: '+1-441-295-4176',
    notes: 'Colombian nationals require full crew visa + yellow fever cert. 28-day avg processing — MUST submit by May 15 to clear in time.',
    urgency: 'urgent',
  },
  {
    id: 'visa-5',
    crewMemberId: 'c8',
    crewMemberName: "Dave O'Brien",
    nationality: 'Ireland',
    destinationCountry: 'Bermuda',
    destinationPort: 'Hamilton',
    visaType: 'Crew Transit Visa',
    status: 'approved',
    documents: [
      { name: 'Valid Passport', required: true, collected: true },
      { name: 'Seaman\'s Book', required: true, collected: true },
      { name: 'Letter of Invitation (Port Agent)', required: true, collected: true },
      { name: 'Passport Photos (2x)', required: true, collected: true },
    ],
    submittedDate: '2026-04-10',
    approvedDate: '2026-04-28',
    expiryDate: '2026-10-28',
    processingDays: 14,
    crewChangeDate: '2026-06-17',
    daysUntilCrewChange: 40,
    portAgent: 'Meyer Agencies Ltd.',
    portAgentContact: '+1-441-295-4176',
    notes: 'Irish nationals need crew transit visa. Approved Apr 28, valid through Oct 28.',
    urgency: 'normal',
  },
  {
    id: 'visa-6',
    crewMemberId: 'c9',
    crewMemberName: 'Kyle Fischer',
    nationality: 'US',
    destinationCountry: 'Brazil',
    destinationPort: 'Santos',
    visaType: 'Crew Visa (VITEM II)',
    status: 'not_started',
    documents: [
      { name: 'Valid Passport', required: true, collected: false },
      { name: 'Seaman\'s Book', required: true, collected: false },
      { name: 'Company Letter', required: true, collected: false },
      { name: 'Passport Photos (2x)', required: true, collected: false },
      { name: 'Vessel Itinerary', required: true, collected: false },
      { name: 'Yellow Fever Vaccination Cert', required: true, collected: false },
    ],
    processingDays: 30,
    crewChangeDate: '2026-09-01',
    daysUntilCrewChange: 116,
    portAgent: 'Inchcape Shipping Services — Santos',
    portAgentContact: '+55-13-3219-4700',
    notes: 'Future voyage planning. US citizens need crew visa for Brazil. 30-day processing. Must submit by Jul 15.',
    urgency: 'normal',
  },
];

export const travelOptionsForDave: TravelOption[] = [
  {
    id: 'opt-d1',
    airline: 'Delta',
    flightNumbers: ['DL 865', 'DL 631'],
    originAirport: 'JAX',
    destinationAirport: 'BDA',
    departDate: '2026-06-15',
    departTime: '09:15',
    arriveDate: '2026-06-15',
    arriveTime: '16:40',
    stops: 1,
    layoverInfo: 'ATL (1h 45m)',
    travelTimeMinutes: 385,
    flightCost: 448,
    fareClass: 'Economy (Marine)',
    refundable: false,
    marineFare: true,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 682,
    tags: ['best_value', 'marine'],
  },
  {
    id: 'opt-d2',
    airline: 'American',
    flightNumbers: ['AA 2110', 'AA 1487'],
    originAirport: 'JAX',
    destinationAirport: 'BDA',
    departDate: '2026-06-15',
    departTime: '06:10',
    arriveDate: '2026-06-15',
    arriveTime: '14:25',
    stops: 1,
    layoverInfo: 'CLT (1h 50m)',
    travelTimeMinutes: 375,
    flightCost: 498,
    fareClass: 'Main Cabin',
    refundable: false,
    marineFare: false,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 732,
    tags: ['fastest'],
  },
  {
    id: 'opt-d3',
    airline: 'JetBlue',
    flightNumbers: ['B6 790', 'B6 247'],
    originAirport: 'JAX',
    destinationAirport: 'BDA',
    departDate: '2026-06-15',
    departTime: '11:30',
    arriveDate: '2026-06-15',
    arriveTime: '18:55',
    stops: 1,
    layoverInfo: 'BOS (2h 15m)',
    travelTimeMinutes: 385,
    flightCost: 472,
    fareClass: 'Blue',
    refundable: false,
    marineFare: false,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 706,
    tags: [],
  },
  {
    id: 'opt-d4',
    airline: 'United',
    flightNumbers: ['UA 1890', 'UA 1784'],
    originAirport: 'JAX',
    destinationAirport: 'BDA',
    departDate: '2026-06-15',
    departTime: '09:00',
    arriveDate: '2026-06-15',
    arriveTime: '17:10',
    stops: 1,
    layoverInfo: 'JFK (2h 30m)',
    travelTimeMinutes: 430,
    flightCost: 562,
    fareClass: 'Economy Flex',
    refundable: true,
    marineFare: false,
    hotelNeeded: true,
    hotelCost: 189,
    groundTransportCost: 45,
    totalCost: 796,
    tags: ['most_flexible'],
  },
];

// ── Port Hotel Options — Hamilton, Bermuda ──────────────────────────
export const portHotels: PortHotel[] = [
  {
    id: 'ph-1',
    name: 'Hamilton Princess & Beach Club',
    address: '76 Pitts Bay Rd, Hamilton HM 08',
    distanceFromPort: '0.3 mi',
    walkingMinutes: 6,
    nightlyRate: 389,
    corporateRate: 279,
    reimbursable: true,
    maxReimbursable: 300,
    amenities: ['wifi', 'pool', 'gym', 'restaurant', 'concierge', 'business_center', 'beach_access'],
    hotelChain: 'Fairmont',
    loyaltyProgram: 'Accor Live Limitless',
    bookingMethod: 'corporate_direct',
    rating: 5,
    crewNotes: 'Walking distance to Front Street Dock. Used for captain handovers. Excellent for short stays.',
    availability: 'available',
    phone: '+1-441-295-3000',
  },
  {
    id: 'ph-2',
    name: 'Grotto Bay Beach Resort',
    address: '11 Blue Hole Hill, Hamilton Parish CR 04',
    distanceFromPort: '8.2 mi',
    walkingMinutes: -1, // not walkable
    nightlyRate: 249,
    corporateRate: 189,
    reimbursable: true,
    maxReimbursable: 300,
    amenities: ['wifi', 'pool', 'beach_access', 'breakfast', 'shuttle', 'kayaks', 'cave_pool'],
    hotelChain: 'Independent',
    bookingMethod: 'phone',
    rating: 4,
    crewNotes: '5 min from BDA airport. Great for crews arriving late. Hotel shuttle to Hamilton at 0700 daily. Room block available.',
    availability: 'available',
    phone: '+1-441-293-8333',
  },
  {
    id: 'ph-3',
    name: 'Rosedon Hotel',
    address: '61 Pitts Bay Rd, Hamilton HM 06',
    distanceFromPort: '0.4 mi',
    walkingMinutes: 8,
    nightlyRate: 295,
    corporateRate: 245,
    reimbursable: true,
    maxReimbursable: 300,
    amenities: ['wifi', 'pool', 'breakfast', 'garden', 'afternoon_tea'],
    hotelChain: 'Independent',
    bookingMethod: 'phone',
    rating: 4,
    crewNotes: 'Quiet, walkable to harbour. Good breakfast included. Popular with officers.',
    availability: 'available',
    phone: '+1-441-295-1640',
  },
  {
    id: 'ph-4',
    name: 'Royal Palms Hotel',
    address: '24 Rosemont Ave, Hamilton HM 06',
    distanceFromPort: '0.6 mi',
    walkingMinutes: 12,
    nightlyRate: 219,
    reimbursable: true,
    maxReimbursable: 300,
    amenities: ['wifi', 'pool', 'breakfast', 'kitchen', 'laundry'],
    hotelChain: 'Independent',
    bookingMethod: 'phone',
    rating: 3,
    crewNotes: 'Budget-friendly, kitchenette in rooms. Good for multi-night stays. Walking distance to harbour.',
    availability: 'limited',
    phone: '+1-441-292-1854',
  },
  {
    id: 'ph-5',
    name: 'Rosewood Bermuda',
    address: '60 Tucker\'s Point Dr, Hamilton Parish HS 02',
    distanceFromPort: '6.5 mi',
    walkingMinutes: -1,
    nightlyRate: 695,
    reimbursable: false,
    amenities: ['wifi', 'pool', 'spa', 'golf', 'beach_access', 'restaurant', 'gym', 'tennis'],
    hotelChain: 'Rosewood',
    loyaltyProgram: 'Rosewood Elite',
    bookingMethod: 'ota',
    rating: 5,
    crewNotes: 'Luxury resort — NOT reimbursable under company policy. Personal use only.',
    availability: 'available',
    phone: '+1-441-298-8000',
  },
  {
    id: 'ph-6',
    name: 'Coco Reef Resort',
    address: '3 Coco Reef Dr, Paget PG 04',
    distanceFromPort: '2.1 mi',
    walkingMinutes: -1,
    nightlyRate: 265,
    corporateRate: 225,
    reimbursable: true,
    maxReimbursable: 300,
    amenities: ['wifi', 'pool', 'beach_access', 'breakfast', 'restaurant'],
    hotelChain: 'Independent',
    bookingMethod: 'phone',
    rating: 3,
    crewNotes: 'Short taxi ride to Hamilton. On the beach. Good value mid-range option.',
    availability: 'available',
    phone: '+1-441-236-5416',
  },
];
